Checking out fb.py from git+git://github.com/emre/fb.py.git#egg=fb.py checkout from git+git://github.com/emre/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Clone in /home/emre/virtualenv/src/fb.py exists, and has correct URL (git://github.com/emre/fb.py.git)
  Updating clone /home/emre/virtualenv/src/fb.py
  Running command git fetch -q
  Running command git checkout -q -f master
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
------------------------------------------------------------
/usr/lib/python2.6/dist-packages/pip.py run on Fri Aug 20 16:15:30 2010
Checking out fb.py from git+git://github.com/emre/fb.py.git#egg=fb.py checkout from git+git://github.com/emre/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Clone in /home/emre/virtualenv/src/fb.py exists, and has correct URL (git://github.com/emre/fb.py.git)
  Updating clone /home/emre/virtualenv/src/fb.py
  Running command git fetch -q
  Running command git checkout -q -f master
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
------------------------------------------------------------
/usr/lib/python2.6/dist-packages/pip.py run on Fri Aug 20 16:16:31 2010
Checking out fb.py from git+git://github.com/egnity/fb.py.git#egg=fb.py checkout from git+git://github.com/egnity/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Git clone in /home/emre/virtualenv/src/fb.py exists with URL git://github.com/emre/fb.py.git
  The plan is to install the Git repository git://github.com/egnity/fb.py.git
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
